//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsunamiGenerator.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsunamiGenerator.Languages.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS &quot;AS IS&quot; AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bsdDisclaimer {
            get {
                return ResourceManager.GetString("bsdDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erase.
        /// </summary>
        public static string eraseButton {
            get {
                return ResourceManager.GetString("eraseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No running Skype client found..
        /// </summary>
        public static string errSkypeNotFound {
            get {
                return ResourceManager.GetString("errSkypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Skype authorization took to long or failed.\r\nPlease make sure that your client is working properly..
        /// </summary>
        public static string errSkypeTookTooLong {
            get {
                return ResourceManager.GetString("errSkypeTookTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flood it!.
        /// </summary>
        public static string floodButton {
            get {
                return ResourceManager.GetString("floodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string languageSelLabel {
            get {
                return ResourceManager.GetString("languageSelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note: changing the language requires program restart.
        /// </summary>
        public static string languageSelRestartNote {
            get {
                return ResourceManager.GetString("languageSelRestartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and I aggree.
        /// </summary>
        public static string legalConfirmButton {
            get {
                return ResourceManager.GetString("legalConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS SOFTWARE WAS MADE FOR EDUCATION AND PEROFRMANCE TESTING PURPOSES ONLY. ANY OTHER USAGE IS NOT RECOMMENDED..
        /// </summary>
        public static string legalWarning {
            get {
                return ResourceManager.GetString("legalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount of messages.
        /// </summary>
        public static string messageAmount {
            get {
                return ResourceManager.GetString("messageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message to send.
        /// </summary>
        public static string messageToSend {
            get {
                return ResourceManager.GetString("messageToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages sent.
        /// </summary>
        public static string msgSent {
            get {
                return ResourceManager.GetString("msgSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip: right-click the status message to wipe all fields!.
        /// </summary>
        public static string rightClickTip {
            get {
                return ResourceManager.GetString("rightClickTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending interval (in milliseconds).
        /// </summary>
        public static string sendingInterval {
            get {
                return ResourceManager.GetString("sendingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settingsLabel {
            get {
                return ResourceManager.GetString("settingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS: connected to skype.
        /// </summary>
        public static string statusConnected {
            get {
                return ResourceManager.GetString("statusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS: done.
        /// </summary>
        public static string statusDone {
            get {
                return ResourceManager.GetString("statusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS: waiting for disclaimer confirmation and skype authorization.
        /// </summary>
        public static string statusWaitingForDCandSkype {
            get {
                return ResourceManager.GetString("statusWaitingForDCandSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS: working....
        /// </summary>
        public static string statusWorking {
            get {
                return ResourceManager.GetString("statusWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop it!.
        /// </summary>
        public static string stopButton {
            get {
                return ResourceManager.GetString("stopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string titleError {
            get {
                return ResourceManager.GetString("titleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string titleWarning {
            get {
                return ResourceManager.GetString("titleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error happened..
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for a user.
        /// </summary>
        public static string userSearch {
            get {
                return ResourceManager.GetString("userSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a message to send..
        /// </summary>
        public static string warnInputMessage {
            get {
                return ResourceManager.GetString("warnInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an username to search for..
        /// </summary>
        public static string warnInputUsername {
            get {
                return ResourceManager.GetString("warnInputUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of messages is invalid..
        /// </summary>
        public static string warnMsgAmountInvalid {
            get {
                return ResourceManager.GetString("warnMsgAmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of messages is too small..
        /// </summary>
        public static string warnMsgAmountTooSmall {
            get {
                return ResourceManager.GetString("warnMsgAmountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sending interval is invalid..
        /// </summary>
        public static string warnSendingIntervalInvalid {
            get {
                return ResourceManager.GetString("warnSendingIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sending interval is too small..
        /// </summary>
        public static string warnSendingIntervalTooSmall {
            get {
                return ResourceManager.GetString("warnSendingIntervalTooSmall", resourceCulture);
            }
        }
    }
}
